version: '3.8'
services:
  db-web:
    image: postgres:latest
    container_name: db-web
    volumes:
      - db-web-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./db-postgres/django/.env

  db-odoo:
    image: postgres:latest
    container_name: db-odoo
    volumes:
      - db-odoo-data:/var/lib/postgresql/data
    expose:
      - "5433"
    ports:
      - 5433:5433
    command: -p 5433
    env_file:
      - ./db-postgres/odoo/.env

  web-django:
    container_name: web-django
    build:
      context: burgers
      dockerfile: ./docker/Dockerfile
    ports:
      - 8001:8001
    env_file:
      - ./burgers/docker/.env
    depends_on:
      - db-web
    links:
      - web-odoo:web-odoo
      - api-flask:api-flask

  web-odoo:
    container_name: web-odoo
    restart: unless-stopped
    build:
      context: ./odoo/
      dockerfile: ./docker/Dockerfile
    ports:
      - 8069:8069
    volumes:
      - odoo-web-data:/var/lib/odoo
    env_file:
      - ./odoo/docker/.env
    depends_on:
      - db-odoo
    links:
      - db-odoo:db-odoo

  api-flask:
    container_name: api-flask
    build:
      context: api-flask
      dockerfile: ./docker/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db-web
      - web-odoo
    links:
      - web-odoo:web-odoo

  nginx:
    container_name: nginx
    build:
      context: nginx
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - web-django
      - web-odoo
    links:
      - web-django:web-django
      - web-odoo:web-odoo

volumes:
  odoo-web-data:
  db-odoo-data:
  db-web-data:
