version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: db
    env_file: 
      - ./db-postgres/docker/.env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  web-django:
    container_name: web-django
    image: javieribarra/burger-django:latest
    ports:
      - 8001:8001
    env_file:
      - ./burgers/docker/.env
    environment:
      - WEB_PORT=8001
    depends_on:
      - db
    links:
      - web-odoo:web-odoo

  web-odoo:
    container_name: web-odoo
    image: javieribarra/burger-odoo:latest
    ports:
      - 8069:8069
    env_file:
      - ./odoo/docker/.env
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - odoo-data:/var/lib/odoo
    entrypoint: "/usr/bin/odoo -c /etc/odoo/odoo.conf"

  nginx:
    container_name: nginx
    image: javieribarra/burger-nginx:latest
    ports:
      - 8000:8000
    depends_on:
      - web-django
      - web-odoo
    links:
      - web-django:web-django
      - web-odoo:web-odoo

volumes:
  odoo-data:
  db-data: