version: '3.8'
services:
  db:
    image: postgres:latest
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=burger
      - POSTGRES_PASSWORD=myburger
    ports:
      - 5432:5432

  web-django:
    container_name: web-django
    ports:
      - 8001:8001
    env_file:
      - ./burgers/docker/.env
    environment:
      - WEB_PORT=8001
    build: 
      context: burgers
      dockerfile: ./Dockerfile
    depends_on:
      - db

  web-odoo:
    image: odoo:14.0
    ports:
      - 8069:8069
    environment:
      - HOST=db
      - USER=burger
      - PASSWORD=myburger
    depends_on:
      - db
    links:
      - db:db

  nginx:
    container_name: nginx
    build:
      context: nginx
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - web-django
      - web-odoo
    links:
      - web-django:web-django
      - web-odoo:web-odoo