version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=burger
      - POSTGRES_PASSWORD=myburger
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  web-django:
    container_name: web-django
    image: javieribarra/burger-django:latest
    ports:
      - 8001:8001
    env_file:
      - ./burgers/docker/.env
    environment:
      - WEB_PORT=8001
    depends_on:
      - db

  web-odoo:
    container_name: web-odoo
    image: javieribarra/burger-odoo:latest
    restart: unless-stopped
    ports:
      - 8069:8069
    environment:
      - HOST=db
      - USER=burger
      - PASSWORD=myburger
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons

  nginx:
    container_name: nginx
    image: javieribarra/burger-nginx:latest
    ports:
      - 8000:8000
    depends_on:
      - web-django
      - web-odoo
    links:
      - web-django:web-django
      - web-odoo:web-odoo

volumes:
  odoo-data:
  db-data: