x-odoo-build: &odoo-build
  context: ./odoo/
  dockerfile: ./docker/Dockerfile

version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: db
    env_file: 
      - ./db-postgres/docker/.env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  web-django:
    container_name: web-django
    build: 
      context: burgers
      dockerfile: ./Dockerfile
    ports:
      - 8001:8001
    env_file:
      - ./burgers/docker/.env
    depends_on:
      - db
    links:
      - web-odoo:web-odoo

  web-odoo:
    container_name: web-odoo
    restart: unless-stopped
    build: 
      context: ./odoo/
      dockerfile: ./Dockerfile
    ports:
      - 8069:8069
    volumes:
      - odoo-web-data:/var/lib/odoo
    env_file:
      - ./odoo/docker/.env
    entrypoint: "/usr/bin/odoo -c /etc/odoo/odoo.conf"
    depends_on:
      - db
    links:
      - db:db
      
  nginx:
    container_name: nginx
    build:
      context: nginx
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - web-django
      - web-odoo
    links:
      - web-django:web-django
      - web-odoo:web-odoo

volumes:
  odoo-web-data:
  db-data: