version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  web-django:
    container_name: web-django
    ports:
      - 8001:8001
    env_file:
      - ./burgers/docker/.env
    environment:
      - WEB_PORT=8001
    build: 
      context: burgers
      dockerfile: ./docker/Dockerfile
    depends_on:
      - postgres

  web-django-2:
    container_name: web-django-2
    ports:
      - 8002:8002
    env_file:
      - ./burgers/docker/.env
    environment:
      - WEB_PORT=8002
    build: 
      context: burgers
      dockerfile: ./docker/Dockerfile
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    build:
      context: nginx
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - web-django
      - web-django-2
    links:
      - web_django:web_django
      - web-django-2:web-django-2