apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose-kubernetes.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: api-flask
  name: api-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-flask
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose-kubernetes.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: api-flask
    spec:
      containers:
        - image: javieribarra/burger-api-flask:latest
          name: api-flask
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
