apiVersion: v1
data:
  ALLOWED_HOSTS: '*'
  DATABASE_NAME: postgres
  DATABASE_URL: postgres://burger:myburger@db:5432/postgres
  DEBUG: "True"
  POSTGRES_PASSWORD: myburger
  POSTGRES_USER: burger
  SECRET_KEY: '...'
  WEB_HOST: 0.0.0.0
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web-django-burgers-docker--env
  name: burgers-docker--env
