apiVersion: v1
data:
  ALLOWED_HOSTS: '*'
  DATABASE_URL: postgres://burger:myburger@db-web:5432/postgres
  DEBUG: "True"
  SECRET_KEY: '...'
  WEB_HOST: 0.0.0.0
  WEB_PORT: "8001"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web-django-burgers-docker--env
  name: burgers-docker--env
