apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose-kubernetes.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: db-odoo
  name: db-odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-odoo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose-kubernetes.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: db-odoo
    spec:
      containers:
        - args:
            - -p
            - "5433"
          env:
            - name: PGDATA
              valueFrom:
                configMapKeyRef:
                  key: PGDATA
                  name: db-postgres-odoo--env
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: db-postgres-odoo--env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: db-postgres-odoo--env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: db-postgres-odoo--env
          image: postgres:latest
          name: db-odoo
          ports:
            - containerPort: 5433
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-odoo-data
      restartPolicy: Always
      volumes:
        - name: db-odoo-data
          persistentVolumeClaim:
            claimName: db-odoo-data
status: {}
