apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose-kubernetes.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: web-odoo
  name: web-odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web-odoo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose-kubernetes.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: web-odoo
    spec:
      containers:
        - env:
            - name: DB_ODOO
              valueFrom:
                configMapKeyRef:
                  key: DB_ODOO
                  name: odoo-docker--env
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  key: HOST
                  name: odoo-docker--env
            - name: PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: PASSWORD
                  name: odoo-docker--env
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: odoo-docker--env
            - name: USER
              valueFrom:
                configMapKeyRef:
                  key: USER
                  name: odoo-docker--env
          image: javieribarra/burger-odoo:latest
          name: web-odoo
          ports:
            - containerPort: 8069
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/odoo
              name: odoo-web-data
      restartPolicy: Always
      volumes:
        - name: odoo-web-data
          persistentVolumeClaim:
            claimName: odoo-web-data
status: {}
