apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: web-django-2
  name: web-django-2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web-django-2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: web-django-2
    spec:
      containers:
        - env:
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  key: ALLOWED_HOSTS
                  name: burgers-docker--env
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_NAME
                  name: burgers-docker--env
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_URL
                  name: burgers-docker--env
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  key: DEBUG
                  name: burgers-docker--env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: WORD
                  name: burgers-docker--env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: burgers-docker--env
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: SECRET_KEY
                  name: burgers-docker--env
            - name: WEB_HOST
              valueFrom:
                configMapKeyRef:
                  key: WEB_HOST
                  name: burgers-docker--env
            - name: WEB_PORT
              value: "8002"
          image: hamburguesas-web-django-2:latest
          name: web-django-2
          ports:
            - containerPort: 8002
          resources: {}
      restartPolicy: Always
status: {}
