apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: web-odoo
  name: web-odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web-odoo
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: web-odoo
    spec:
      containers:
        - env:
            - name: HOST
              value: db
            - name: PASSWORD
              value: myburger
            - name: USER
              value: burger
          image: javieribarra/burger-odoo:latest
          name: web-odoo
          ports:
            - containerPort: 8069
          resources: {}
      restartPolicy: Always
status: {}
