apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose-kubernetes.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: web-django
  name: web-django
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web-django
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose-kubernetes.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: web-django
    spec:
      containers:
        - env:
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  key: ALLOWED_HOSTS
                  name: burgers-docker--env
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_URL
                  name: burgers-docker--env
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  key: DEBUG
                  name: burgers-docker--env
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: SECRET_KEY
                  name: burgers-docker--env
            - name: WEB_HOST
              valueFrom:
                configMapKeyRef:
                  key: WEB_HOST
                  name: burgers-docker--env
            - name: WEB_PORT
              valueFrom:
                configMapKeyRef:
                  key: WEB_PORT
                  name: burgers-docker--env
          image: javieribarra/burger-django:latest
          name: web-django
          ports:
            - containerPort: 8001
          resources: {}
      restartPolicy: Always
status: {}
