# Generated by Django 3.2 on 2022-11-09 12:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('state', models.BooleanField(default=True)),
                ('CuartoDeLibra', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('Quinoa', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('address', models.CharField(max_length=200)),
                ('attendees', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)])),
                ('creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('measurement', models.CharField(choices=[('Kg', 'Kilograms'), ('gr', 'Grams'), ('Lts', 'Liters'), ('Unt', 'Unitary')], default='Kg', max_length=3)),
                ('unitary_cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('avg_consumption_pp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.event')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ingredient')),
            ],
        ),
    ]
