# Generated by Django 3.2 on 2022-10-18 23:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_event_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('measurement', models.CharField(choices=[('Kg', 'Kilograms'), ('gr', 'Grams'), ('Lts', 'Liters'), ('Unt', 'Unitary')], default='Kg', max_length=3)),
                ('unitary_cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('avg_consumption_pp', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ingredient'),
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
    ]
