name: ci

on:
  push:
    branches: ["main", "milestone_1", "milestone_2", "milestone_3", "milestone_4"]
    paths-ignore: [ '**/README.md', '**/env.example', '**/django.yml', '**/docker-compose.yml', '**/docker-compose-old.yml', '/kubernetes' ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push docker django
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:burgers"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/burger-django:latest
      -
        name: Build and push docker nginx
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:nginx"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/burger-nginx:latest
      -
        name: Build and push docker odoo
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:odoo"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/burger-odoo:latest